version: '3.7'

services:
  kafka:
    container_name: kafka
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
       ADVERTISED_HOST: kafka
       ADVERTISED_PORT: 9092

#  websocketstream:
#    container_name: websocketstream
#    build:
#      context: ./websocketstream
#      dockerfile: Dockerfile
#    logging:
#      driver: none
#    depends_on:
#      - kafka
#      - testproducer
#    links:
#      - kafka:kafka
#      - testproducer:testproducer

#  testproducer:
#    container_name: testproducer
#    build:
#      context: ./testproducer
#      dockerfile: Dockerfile
#    logging:
#      driver: none

  poloniexstream:
    container_name: poloniexstream
    build:
      context: ./poloniexstream
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: none
    depends_on:
      - kafka
    links:
      - kafka:kafka

#  kafkacat:
#    container_name: kafkacat
#    image: confluentinc/cp-kafkacat
#    command: >
#      /bin/bash -c "
#        sleep 15;
#        kafkacat -b kafka:9092 -C -t poloniex;
#      "
#    depends_on:
#      - kafka
#    links:
#      - kafka:kafka

#  mongo:
#    image: mongo
#    restart: always
#    command: --smallfiles
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#    - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    depends_on:
#    - mongo
#    links:
#    - mongo:mongo

  kafkamongodbstream:
    container_name: kafkamongodbstream
    build:
      context: ./kafkamongodbstream
      dockerfile: Dockerfile
    environment:
      TOPIC: poloniex
    restart: unless-stopped
#    logging:
#      driver: none
    depends_on:
    - kafka
#    - mongo
    links:
    - kafka:kafka
#    - mongo:mongo
